name: paper
on:
  push:
    paths: ['paper/**']
  pull_request:
    paths: ['paper/**']
permissions:
  contents: read
jobs:
  paper:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: xu-cheng/latex-action@6549dc21effb2730855a1281407ecfcececc6c1b # 4.1.0
        with: { root_file: paper/main.tex }
